### ISSUE TITLE
[DevOps] Create Discord notification workflow

### ISSUE THREAD

**Issue by jji05** [uoa-compsci399-2025-s1/capstone-project-2025-s1-team-8#5]
### Description:

It would be great to have a notification on Discord whenever someone creates a new pull request. 

Requires creating a `DISCORD_WEBHOOK_URL` secret in the GitHub action secrets menu in Settings. 

```yml
name: Pull Request Notifications

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  pull_request_created:
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened'
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Pull request opened: ${{ github.event.pull_request.title }} | Link: [View Pull Request](${{ github.event.pull_request.html_url }})"

  pull_request_merged:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Pull request merged: ${{ github.event.pull_request.title }}"
```

### Definition of Done:

- [ ] PR reviewed
